### ISSUE TITLE
Windows + linux support

### ISSUE THREAD

**Issue by saulshanabrook** [jenslind/electron-gh-releases#1]
How feasible would adding windows and linux support be?

**Comment by jenslind** [comment]
Windows will be doable as soon as Electron supports it and it's fully documented. Linux handles updates in a different way and will there for probably never be supported in Electrons `auto-updater`.

Discussions regarding this:
https://github.com/atom/electron/issues/939
https://github.com/atom/electron/issues/1479

**Comment by saulshanabrook** [comment]
Thanks!
