### ISSUE TITLE
Unable to get latest release tag from Github

### ISSUE THREAD

**Issue by bitomule** [jenslind/electron-gh-releases#13]
I get this error after updating to electron 0.36.0.

This is the full error returned on _getLatestTag method:

```
{ [ReadError: unexpected end of file]
  code: 'Z_BUF_ERROR',
  message: 'unexpected end of file',
  host: 'github.com',
  hostname: 'github.com',
  method: 'HEAD',
  path: '/myapp/myapp-desktop/releases/latest' }
```

I updated electron trying to find if the issue with quitAndUpdate not working was fixed.

**Comment by jenslind** [comment]
Thanks for reporting. It has been fixed in `got` now. Just do a clean npm install and it should work. :)

**Comment by bitomule** [comment]
Thanks!!
