### ISSUE TITLE
The zipUrl ... is a invalid release URL

### ISSUE THREAD

**Issue by manosim** [jenslind/electron-gh-releases#17]
Hello there, I've been using electron-gh-releases for some time now (auto-updated about 4 new versions with success) for [Gitify](https://github.com/ekonstantinidis/gitify/).

So the procedure I follow every time is:
- Use `electron-packager`
- Code sign the app
- Compress the app

I'm about to release a new version of Gitify, reaching version **1.0.0** from **0.0.19** and I'm trying to test if the autoupdater works but it looks like it is not working. I've got a test repository with version **1.0.1** release(with a tag and auto_update.json).

In order to test it, I've also built version **1.0.0** but when it loads I'm getting the following error:

```
Error: The zipUrl (https://github.com/ekonstantinidis/gitify-test/releases/download/1.0.1/gitify-osx.zip) is a invalid release URL. Status: false
```

If you go to the zipUrl you will see that it is working fine. Any ideas on what could be wrong?

Ps. Thank you for the great work on the package!

**Comment by jenslind** [comment]
Hello, thanks for reporting.

It's the regex match on line [87](https://github.com/jenslind/electron-gh-releases/blob/master/src/GhReleases.js#L87) that fails. Currently the version tag must contain a `v` it seems, thats why the regex check fails. But a semver version without `v` is still valid, so we should fix the regex.

**Comment by manosim** [comment]
Hello @jenslind! Not sure if it helps but it worked fine for updates where the tag was:
- `0.0.16` to `0.0.17`
- `0.0.17` to `0.0.18`
- `0.0.18` to `0.0.19`

Thank you for your quick reply!

**Comment by jenslind** [comment]
How we parse the url was changed in `2.0.2` I think the older version allowed version tags without `v`.

**Comment by manosim** [comment]
I can open a PR to make the `v` optional if that helps?

``` diff
-const REGEX_ZIP_URL = /\/v(\d+\.\d+\.\d+)\/.*\.zip/
+const REGEX_ZIP_URL = /\/(v)?(\d+\.\d+\.\d+)\/.*\.zip/
```

Update: Link to test the regex: https://regex101.com/r/jY6tG4/1

**Comment by jenslind** [comment]
👍 A PR would be much appreciated!

**Comment by manosim** [comment]
Done! #18
