### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by bayleedev** [jenslind/electron-gh-releases#21]
When you call `check` on the API it returns an exception if they aren't window/mac.

https://github.com/jenslind/electron-gh-releases/blob/master/src/GhReleases.js#L105-L106

Is it possible to to still check if an update is available, but have `download` do this check? That way I can alert the users "there IS an update, but you need to download it manually" instead of "you don't support updates, and I'm not sure if there is one" ?

**Comment by jenslind** [comment]
👍 

I think the easiest would be to move the platform check [here](https://github.com/jenslind/electron-gh-releases/blob/master/src/GhReleases.js#L127-L128) (before `setFeedURL`) And then return the error and status can still be `true`.
