### ISSUE TITLE
no errors are caught

### ISSUE THREAD

**Issue by dylang** [jenslind/electron-gh-releases#8]
`electron-gh-releases` needs to use `autoUpdater.on('error', cb)` to catch update errors.

**Comment by jenslind** [comment]
I don't see the point of catching these errors in `electron-gh-releases`.
You should catch these errors yourself, in your app.

``` Javascript
var updater = new GhReleases(opts)
updater.autoUpdater.on('error', cb)
```

**Comment by dylang** [comment]
Perfect, I didn't realize `autoUpdater` was exposed.
