### ISSUE TITLE
Publish the compiled files

### ISSUE THREAD

**Issue by maxclaus** [jenslind/electron-gh-releases#9]
Is there a reason you are not publishing the compiled files (ES5 support)?

Even being possible include this package in my babel configuration like this example below. I usually have seen people providing the compiled version.

``` json
"ignore": "/node_modules\/(?!electron-gh-releases)/"
```

**Comment by jenslind** [comment]
I'm not sure if I understand you correctly, but the compiled version should be published?
https://github.com/jenslind/electron-gh-releases/blob/master/GhReleases.js

**Comment by maxclaus** [comment]
Sorry I didn't saw the compiled file. But for some reason I was getting some erros of "unexpected word" before including the `electron-gh-releases` in the babel builder. I will test it today again.

**Comment by maxclaus** [comment]
Sorry again. I installed the module again and now is working. I probably had some networking problem during the previous installation and was missing some files. Anyway, I'm going to close this issue since everything is right.

**Comment by jenslind** [comment]
>  But for some reason I was getting some erros of "unexpected word" 

You were probably using `2.0.0`.
I missed to update some dependencies before releasing :goat:
All should be good in `2.0.1` :dancer:
